### ISSUE TITLE
#build faild 

### ISSUE THREAD

**Issue by aaron-codes** [wwsun/starter-node-react#1]
npm run build output:

> webpack --config config/webpack.config.js

Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.12.2
Time: 647ms
    + 1 hidden modules

ERROR in Loader /Users/ouyangxian/Documents/git_workspace/starter-node-react/node_modules/babel/index.js didn't return a function

**Comment by wwsun** [comment]
sorry, you can `npm i babel-loader --save-dev` to solve this problem

**Comment by aaron-codes** [comment]
solve, tks.
