### ISSUE TITLE
路径引用错误

### ISSUE THREAD

**Issue by dwqs** [wwsun/starter-node-react#3]
在文件`src/client/scripts/client.js`中

> import App from '../../app';

应该是

> import App from '../../app/app';

另外 虽然使用了 `babel/register`  但是Node端还是不支持 es6  

[require('babel/register') doesn't work](http://stackoverflow.com/questions/29207878/requirebabel-register-doesnt-work)

`package.json`中，

> "start": "node src/server/index.js",

应该加上 `--harmony`

**Comment by wwsun** [comment]
1. `app`下面有`index.js`
2. 可以使用es6写node代码
3. 确保你的Node升级到 `v4.2`以上版本
4. 确保你的Babel升级到 `v6`以上版本

**Comment by dwqs** [comment]
谢谢  之前没看仔细
