### ISSUE TITLE
babel

### ISSUE THREAD

**Issue by Ricko53** [wwsun/starter-node-react#4]
npm start 的时候遇到了

```
Error: Cannot find module 'babel/register' 
```

查了一下应该是babel-register独立出去了 install 改 require('babel-register');

然后遇到一个问题 node v4.1.2

```
/Users/tommy/CodeHome/react/starter-node-react/src/server/server.js:3
import path from 'path';
^^^^^^
```

**Comment by wwsun** [comment]
Bug fix, using `babel-node` as the server-side runtime
